from chatgpt_voice_assistant.exceptions.listener_error import ListenerError


class ListenerFatalError(ListenerError):
    pass
